apiVersion: v1
kind: Service
metadata:
  name: flask-rest-api
  labels:
    app: flask-rest-api
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: flask-rest-api